AWSTemplateFormatVersion: 2010-09-09
Description: NAT Gateway Stack for private subnet.

Parameters:
  PublicSubnetId:
    Type: String

Resources:
  NATGatewayEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: Lab1-NATGatewayEIP

  NATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NATGatewayEIP.AllocationId
      SubnetId: !Ref PublicSubnetId
      Tags:
        - Key: Name
          Value: Lab1-NATGateway

Outputs:
  NatGatewayId:
    Value: !Ref NATGateway