AWSTemplateFormatVersion: '2010-09-09'
Description: main stack

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://nhom16-bucket.s3.us-east-1.amazonaws.com/vpc.yml

  NATStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://nhom16-bucket.s3.us-east-1.amazonaws.com/nat-gateway.yml
      Parameters:
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        PublicSubnetId: !GetAtt VPCStack.Outputs.PublicSubnetId

  SGStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://nhom16-bucket.s3.us-east-1.amazonaws.com/security-groups.yml
      Parameters:
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        MyIp: 171.236.48.98/32

  RouteTableStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://nhom16-bucket.s3.us-east-1.amazonaws.com/route-tables.yml
      Parameters:
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        PublicSubnetId: !GetAtt VPCStack.Outputs.PublicSubnetId
        PrivateSubnetId: !GetAtt VPCStack.Outputs.PrivateSubnetId
        IGWId: !GetAtt VPCStack.Outputs.IGWId
        NatGatewayId: !GetAtt NATStack.Outputs.Nhom16NatGatewayId

  EC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://nhom16-bucket.s3.us-east-1.amazonaws.com/ec2.yml
      Parameters:
        PublicSubnetId: !GetAtt VPCStack.Outputs.PublicSubnetId
        PrivateSubnetId: !GetAtt VPCStack.Outputs.PrivateSubnetId
        PublicSG: !GetAtt SGStack.Outputs.Nhom16PublicSecurityGroup
        PrivateSG: !GetAtt SGStack.Outputs.Nhom16PrivateSecurityGroup
        KeyName: nhom16-key
