AWSTemplateFormatVersion: '2010-09-09'
Description: NAT Gateway + Elastic IP.

Parameters:
  VPCId:
    Type: String
  PublicSubnetId:
    Type: String

Resources:
  Nhom16NatEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: Nhom16NatEIP

  Nhom16NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt Nhom16NatEIP.AllocationId
      SubnetId: !Ref PublicSubnetId
      Tags:
        - Key: Name
          Value: Nhom16NatGateway

Outputs:
  Nhom16NatGatewayId:
    Value: !Ref Nhom16NatGateway
