AWSTemplateFormatVersion: 2010-09-09
Description: Security Groups Stack for public and private EC2 instances.

Parameters:
  VpcId:
    Type: String

Resources:
  PublicSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Allow SSH access from specific CIDR
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: Lab1-PublicSecurityGroup

  PrivateSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Allow access from Public EC2 instance
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !Ref PublicSecurityGroup
      Tags:
        - Key: Name
          Value: Lab1-PrivateSecurityGroup

Outputs:
  PublicSecurityGroupId:
    Value: !Ref PublicSecurityGroup
  PrivateSecurityGroupId:
    Value: !Ref PrivateSecurityGroup